### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by ramonQAQ** [Nick2bad4u/BHBot#37]
i opened the .exe file for the first time i get a downloader of some sort i click on start free trial it says it started and then it closed and now everytime i open nothing happens

**Comment by Nick2bad4u** [comment]
> i opened the .exe file for the first time I get a downloader of some sort i click on start free trial it says it started and then it closed and now every time i open nothing happens.

Thats for the SimpleGUI. Do you have python installed on your pc? If so, that is the only way to get the Gui entry again for the key. I can give you the key. If you need it.

However, If you are having issues with the .exe version, I recommend that you install python 3.11.8 manually from [here](https://www.python.org/downloads/release/python-3118/).

Then you can download the "source code" under the releases section (or you can click [here](https://github.com/Nick2bad4u/BHBot/archive/refs/tags/BHBOT-vivi.zip)) and run the bot manually by double clicking gui.pyw.

**Comment by ramonQAQ** [comment]
> > i opened the .exe file for the first time I get a downloader of some sort i click on start free trial it says it started and then it closed and now every time i open nothing happens.
> 
> **### This may be due to windows defender blocking the file. Check this first as this is most likely the issue causing it to autoclose. You may have to manually allow via defender and then redownload it.**
> 
> The key is for the SimpleGUI. Do you have python installed on your pc? If so, that is the only way to get the Gui entry again for the key. I can give you the key. If you need it.
> 
> However, if you are having issues with the .exe version, I recommend that you install python 3.11.8 manually from [here](https://www.python.org/downloads/release/python-3118/). The .exe version is very unstable and not ever going to be as good as the regular python version. Although some people have had success with it, others have not. Not sure why at this point. You can also install python and try to run the .exe version again if you want, but I don't recommend it.
> 
> Then you can download the "source code" under the releases section (or you can click [here](https://github.com/Nick2bad4u/BHBot/archive/refs/tags/BHBOT-vivi.zip)) and run the bot manually by double clicking gui.pyw.

ty it worked now and ty for returning to developing the bot i really appreciate it
