### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by ICEWOLFL** [Nick2bad4u/BHBot#97]
Traceback (most recent call last):
  File "gui.pyw", line 206, in <module>
  File "gui.pyw", line 29, in __init__
  File "gui.pyw", line 81, in create_window
  File "utils.py", line 210, in update_window
  File "utils.py", line 177, in language
  File "utils.py", line 173, in get_language
StopIteration

**Comment by Nick2bad4u** [comment]
> Traceback (most recent call last): File "gui.pyw", line 206, in File "gui.pyw", line 29, in **init** File "gui.pyw", line 81, in create_window File "utils.py", line 210, in update_window File "utils.py", line 177, in language File "utils.py", line 173, in get_language StopIteration

Did you follow the new installation instructions and install python and do the install requirements command?

**Comment by ICEWOLFL** [comment]
Nuthing working add me on discord to help me username is icewolf56

**Comment by kentrellgaulden** [comment]
> Traceback (most recent call last): File "gui.pyw", line 206, in File "gui.pyw", line 29, in **init** File "gui.pyw", line 81, in create_window File "utils.py", line 210, in update_window File "utils.py", line 177, in language File "utils.py", line 173, in get_language StopIteration

did u even try the source code or just give up when the exe failed

**Comment by Nick2bad4u** [comment]
> Nuthing working add me on discord to help me username is icewolf56

Did you try the source code w/ the installation instructions?

**Comment by mikejasons** [comment]
hi, I have the same problem. unlike the other guy I have tried the source code which doesn't run at all ;(

**Comment by Nick2bad4u** [comment]
> hi, I have the same problem. unlike the other guy I have tried the source code which doesn't run at all ;( ![image](https://private-user-images.githubusercontent.com/172581426/339346627-4d6e00d6-5d28-4bc3-98a3-7fa9724793c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTUwNTcsIm5iZiI6MTcxODI5NDc1NywicGF0aCI6Ii8xNzI1ODE0MjYvMzM5MzQ2NjI3LTRkNmUwMGQ2LTVkMjgtNGJjMy05OGEzLTdmYTk3MjQ3OTNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNjA1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDZjNGUyNzNhMjQ2YWMxOTE5NjIwZTAzNTY0ZTNkN2UxOWZmNmEyMThiNDY4Y2MwMTE5MjQxMWJkOGRjNDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-6DnviiBobp-TBFb7U75c-z_MOTZ6gfCdqg0E8g-40I)

What version of python are you running?

**Comment by mikejasons** [comment]
3.12.4

**Comment by Nick2bad4u** [comment]
> 3.12.4

Try 3.11.8

**Comment by mikejasons** [comment]
same issue

**Comment by Nick2bad4u** [comment]
> same issue

Trying version 3.11.8?

**Comment by Nick2bad4u** [comment]
> same issue

We had another person with same error and was able to fix it. Asking that person now if they can tell me what they did to fix it as this doesnt occur with many ppl.

**Comment by Nick2bad4u** [comment]
> Traceback (most recent call last): File "gui.pyw", line 381, in File "gui.pyw", line 134, in **init** File "gui.pyw", line 237, in create_window File "utils.py", line 236, in update_window File "utils.py", line 193, in language File "utils.py", line 189, in get_language StopIteration
> 
> How to fix this pls help me guys

Try running the bot directly via python if you know how.

**Comment by Nick2bad4u** [comment]
> hi, I have the same problem. unlike the other guy I have tried the source code which doesn't run at all ;( ![image](https://private-user-images.githubusercontent.com/172581426/339346627-4d6e00d6-5d28-4bc3-98a3-7fa9724793c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzOTkxODAsIm5iZiI6MTcyNTM5ODg4MCwicGF0aCI6Ii8xNzI1ODE0MjYvMzM5MzQ2NjI3LTRkNmUwMGQ2LTVkMjgtNGJjMy05OGEzLTdmYTk3MjQ3OTNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QyMTI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzI3YjAwY2FkMzU3NTQ4NWEzOGZlNmE4MjJmODAwMGQ5OTg1MTg0MzEzY2FjM2Y2ZGE1Mzg0YTFjMDM1MWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SPy8V849jrfSzxRd_9Gc5NMI0_qqBLqXFPSLNVHUBJc)

Have you done this?
If you have -

You need to install the dependencies.

go to Python and type "pip install -r requirements.txt" while in the source code folder.
